// File generated by FlutterFire CLI + ajout config Android/iOS manuelle
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⭐ CONFIGURATION ANDROID (depuis google-services.json)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNUfr7ky78ZuI-11f5zUnPcMdIsZbVe0',
    appId: '1:651209584171:android:b1a891302babe1d2d6c46e',
    messagingSenderId: '651209584171',
    projectId: 'pragmatic-bongo-494111-s1',
    storageBucket: 'pragmatic-bongo-494111-s1.firebasestorage.app',
  );

  // ⭐ CONFIGURATION iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0BLFPUXHgBMWXduhX7pejho5j92hDgo',
    appId: '1:651209584171:ios:ca5c69d6c409ac52d6c46e',
    messagingSenderId: '651209584171',
    projectId: 'pragmatic-bongo-494111-s1',
    storageBucket: 'pragmatic-bongo-494111-s1.firebasestorage.app',
    iosBundleId: 'com.example.abFitnessFamily',
  );

  // ⭐ CONFIGURATION WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1INBLD731N2hRotjdhAK8RHHfdb6ptc',
    appId: '1:651209584171:web:e6c3eb41493cca46d6c46e',
    messagingSenderId: '651209584171',
    projectId: 'pragmatic-bongo-494111-s1',
    authDomain: 'pragmatic-bongo-494111-s1.firebaseapp.com',
    storageBucket: 'pragmatic-bongo-494111-s1.firebasestorage.app',
    measurementId: 'G-5HZMVXSW0P',
  );

  // ⭐ CONFIGURATION macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0BLFPUXHgBMWXduhX7pejho5j92hDgo',
    appId: '1:651209584171:ios:ca5c69d6c409ac52d6c46e',
    messagingSenderId: '651209584171',
    projectId: 'pragmatic-bongo-494111-s1',
    storageBucket: 'pragmatic-bongo-494111-s1.firebasestorage.app',
    iosBundleId: 'com.example.abFitnessFamily',
  );

  // ⭐ CONFIGURATION Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR1INBLD731N2hRotjdhAK8RHHfdb6ptc',
    appId: '1:651209584171:web:b85d4299e9f30015d6c46e',
    messagingSenderId: '651209584171',
    projectId: 'pragmatic-bongo-494111-s1',
    authDomain: 'pragmatic-bongo-494111-s1.firebaseapp.com',
    storageBucket: 'pragmatic-bongo-494111-s1.firebasestorage.app',
    measurementId: 'G-WXEC7NX7H8',
  );
}
